### ISSUE TITLE
OPC-DA Server

### ISSUE THREAD

**Issue by yzpniceboy** [SetGeek/OPC-DA#1]
你好作者，请教下是否有 基于java的OPC-DA2.0 Server 的方案？
目前碰到的问题是 java服务器端的数据，要让C#客户端通过OPC-DA2.0的协议来读取，
目前一头雾水，请教下，谢谢

**Comment by SetGeek** [comment]
既然是基于OPC-DA2.0，那么应该跟服务端使用什么语言没关系吧，这里不知道是我没有理解你的意思，还是其他的问题

**Comment by SetGeek** [comment]
既然是基于OPC-DA2.0，那么应该跟服务端使用什么语言没关系吧，这里不知道是我没有理解你的意思，还是其他的问题

**Comment by SetGeek** [comment]
如果只是开发客户端，那就直接使用服务器模拟软件，配置DCOM就能使用了

**Comment by yzpniceboy** [comment]
你好，可能我没有表述清除我的意思，我第一次开发设计OPC,我的需求是：别人开发的客户端需要通过OPC-DA2.0的协议来访问我的java WEB服务器的数据。
Q1:我是不是应该在java web服务器端开发一个OPC-DA2.0的服务器端，来供别人的客户端连接和读取数据？
Q2:请教下是否有基于java的OPC-DA2.0 Server 的实现方案？

**Comment by yzpniceboy** [comment]
我对需求的理解是，我是不是应该开发一个 OPC-DA2.0 服务器端，这样别人的客户端才能访问到我的数据？

**Comment by yzpniceboy** [comment]
我感觉我的需求可能就是我要用 java 开发一个OPC-DA2.0 服务器端，而不是客户端，这样别人才能通过OPC-DA2.0 协议读到我的数据？

**Comment by SetGeek** [comment]
我暂时没有找到用java实现OPC-DA服务的方案，有两种方式参考，一种是用java开发opc-da客户端，将数据写入第三方的OPC服务器，别人再从OPC服务获取，另一种是使用OPC UA

**Comment by yzpniceboy** [comment]
我一开始的思路是 用VC++实现一个标准的OPC DA2.0服务器，然后我的java web往里面写数据，别人的OPC客户端从里面读数据，感觉这样好像不太对、、

**Comment by SetGeek** [comment]
我认为这种思路可以的，OPC服务端负责数据存储与转发

**Comment by yzpniceboy** [comment]
谢谢，思路有点清晰了！
第三方 OPC DA2.0服务器 有没有开源免费的？
